set_property SRC_FILE_INFO {cfile:d:/study/digital_system/vhdl_studies/DS_lab2/DS_lab2.srcs/sources_1/bd/design_3/ip/design_3_clk_wiz_0_0/design_3_clk_wiz_0_0/design_3_clk_wiz_0_0_in_context.xdc rfile:../../../DS_lab2.srcs/sources_1/bd/design_3/ip/design_3_clk_wiz_0_0/design_3_clk_wiz_0_0/design_3_clk_wiz_0_0_in_context.xdc id:1 order:EARLY scoped_inst:design_3_i/clk_wiz_0} [current_design]
set_property SRC_FILE_INFO {cfile:D:/study/digital_system/vhdl_studies/DS_lab2/DS_lab2.srcs/constrs_1/imports/DS_lab2_tutorial_files/pynq-z2.xdc rfile:../../../DS_lab2.srcs/constrs_1/imports/DS_lab2_tutorial_files/pynq-z2.xdc id:2} [current_design]
current_instance design_3_i/clk_wiz_0
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.000 [get_ports -no_traverse {}]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk_in1] -edges {1 2 3} -edge_shift {0.000 16.000 32.000} [get_ports {}]
current_instance
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H16   IOSTANDARD LVCMOS33 } [get_ports { clk_in1_0 }]; #IO_L13P_T2_MRCC_35 Sch=sysclk
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R14   IOSTANDARD LVCMOS33 } [get_ports {oLed0_0 }]; #IO_L6N_T0_VREF_34 Sch=led[0]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P14   IOSTANDARD LVCMOS33 } [get_ports {oLed1_0 }]; #IO_L6P_T0_34 Sch=led[1]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN N16   IOSTANDARD LVCMOS33 } [get_ports {oLed2_0 }]; #IO_L21N_T3_DQS_AD14N_35 Sch=led[2]
set_property src_info {type:XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M14   IOSTANDARD LVCMOS33 } [get_ports {oLed3_0 }]; #IO_L23P_T3_35 Sch=led[3]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D19   IOSTANDARD LVCMOS33 } [get_ports { iRst_0 }]; #IO_L4P_T0_35 Sch=btn[0]
