# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/DS_lab2_tutorial_files/pynq-z2.xdc

# Block Designs: bd/design_3/design_3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3 || ORIG_REF_NAME==design_3} -quiet] -quiet

# IP: bd/design_3/ip/design_3_assign_3_0_0/design_3_assign_3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_assign_3_0_0 || ORIG_REF_NAME==design_3_assign_3_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_clk_wiz_0_0/design_3_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_clk_wiz_0_0 || ORIG_REF_NAME==design_3_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/design_3/design_3_ooc.xdc
